name: cdvae1
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24.4
  - pandas=2.0.3
  - scipy=1.15.1
  - networkx=3.1
  - setuptools=72.2.0
  - sympy=1.13.2
  - tqdm=4.66.5
  - pytorch
  - torchvision
  - pytorch-lightning=2.4.0
  - scikit-learn=1.3.2
  - pytest=8.3.3
  - pymatgen=2023.8.10
  - pip
  - pip:
    - matminer==0.9.3
    - omegaconf==2.3.0
    - p-tqdm==1.4.2
    - python-dotenv==1.0.1
    - SMACT==2.5.5
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18s